config/routes.rb
Rails.application.routes.draw do
  
  resources :products
  get 'resolved' => 'records#resolved'
  get 'records/resolved'
  get 'active' => 'records#active'
  get 'records/active'
  get 'search' => 'records#search'
  get 'records/search'
  
  resources :records do
    collection do
      get 'narrow_choices', to: "records#narrow_choices"
    end 
  end
  
  root 'records#index'

end

app/models/record.rb
class Record < ApplicationRecord
    
    scope :serialNum, -> (serialNum) { where serialNum: serialNum }
    scope :supplier, -> (supplier) { where supplier: supplier }
    scope :product, -> (product) { where product: product }
    scope :status, -> (status) { where status: status }
    
    before_update :log_changes
    after_initialize :set_defaults, unless: :persisted?
    
    validates :serialNum, length: {maximum: 16}
    validates :product, length: {maximum: 16}, presence: true
    validates :removalDate, presence: true
    validates :qn, presence: true
    validates :supplier, length: {maximum: 16}, presence: true
    validates :owner, length: {maximum: 16}
    validates :partNum, length: {maximum: 16}
    
    # These are the possible statuses supported in the form
    # FIXME : Allow users to add/subtract from this list
    STATUSES = [ "Waiting to ship", "Shipped", "Received" ]
    
    # This converts to csv with explicit column headings and each member explicit as well
    def self.to_csv(records = self.all, options = {})
        
        all_headers = Array.[]("Serial Number", "Removal Date", 
        "Removal Location", "Program", "Product", "Part Number", "Supplier", 
        "Owner", "Status", "PW QN", "UTAS D3 QN", "UTAS V2 QN", "PW PO", "UTAS PO", 
        "Action Required", "Removal Reason", "Comments", "Resolved?")
        
        cols_of_interest = Array.[]('serialNum', 'removalDate', 'removalLocation', 
        'program', 'product', 'partNum', 'supplier', 'owner', 'status', 'pwQN', 
        'd3QN', 'v2QN', 'pwPO', 'utasPO', 'actionReq', 'removalReason', 
        'comments', 'resolved')
        
        CSV.generate(options) do |csv|
            csv << all_headers
            records.each do |record|
                csv << record.attributes.values_at(*cols_of_interest)
            end
        end
    end
    
    # defaults are set so the log_changes function does not break
    def set_defaults
        self.fullChangelog = ""
        self.serialNum = "" if !self.serialNum
        self.removalDate = "" if !self.removalDate
        self.removalLocation = "" if !self.removalLocation
        self.program = "" if !self.program
        self.product = "" if !self.product
        self.partNum = "" if !self.partNum
        self.owner = "" if !self.owner 
        self.status = "" if !self.status 
        self.qn = "" if !self.qn
        self.d3QN = "" if !self.d3QN 
        self.v2QN = "" if !self.v2QN
        self.pwPO = "" if !self.pwPO
        self.utasPO = "" if !self.utasPO
        self.actionRequiredBy = "" if !self.actionRequiredBy
        self.removalReason = "" if !self.removalReason 
        self.comments = "" if !self.comments
        
    end
    
    # I tried to come up with a fancier/refactored way to do this but couldn't 
    # figure it out while still using _was
    # FIXME : Take a second look (use a helper that takes the 3 as arguments?)
    def log_changes 
        if self.comments_changed?
            then 
                timeNow = Time.now
                self.fullChangelog = "<br>Comments " +  
                " updated on " + "#{timeNow.month} / " + 
                "#{timeNow.day} / " + "#{timeNow.year} " + "</br>" +
                "#{self.fullChangelog}"
        end
        if self.removalReason_changed?
            then 
                timeNow = Time.now
                self.fullChangelog = "<br>Removal reason " +  
                " updated on " + "#{timeNow.month} / " + 
                "#{timeNow.day} / " + "#{timeNow.year} " + "</br>" +
                "#{self.fullChangelog}"
        end
        if self.actionRequiredBy_changed?
            then 
                timeNow = Time.now
                self.fullChangelog = "<br>Action Required " +  
                " updated on " + "#{timeNow.month} / " + 
                "#{timeNow.day} / " + "#{timeNow.year} " + "</br>" +
                "#{self.fullChangelog}"
        end
        if self.utasPO_changed?
            then 
                timeNow = Time.now
                self.fullChangelog = "<br>UTAS PO changed from:  " + 
                "#{self.utasPO_was}" + "     to  " + "#{self.utasPO}" + 
                " on " + "#{timeNow.month} / " + 
                "#{timeNow.day} / " + "#{timeNow.year} " + "</br>" +
                "#{self.fullChangelog}"
        end
        if self.pwPO_changed?
            then 
                timeNow = Time.now
                self.fullChangelog = "<br>PW PO changed from:  " + 
                "#{self.pwPO_was}" + "    to  " + "#{self.pwPO}" + 
                " on " + "#{timeNow.month} / " + 
                "#{timeNow.day} / " + "#{timeNow.year} " + "</br>" +
                "#{self.fullChangelog}"
        end
        if self.v2QN_changed?
            then 
                timeNow = Time.now
                self.fullChangelog = "<br>UTAS V2 QN changed from:  " + 
                "#{self.v2QN_was}" + "    to  " + "#{self.v2QN}" + 
                " on " + "#{timeNow.month} / " + 
                "#{timeNow.day} / " + "#{timeNow.year} " + "</br>" +
                "#{self.fullChangelog}"
        end
        if self.d3QN_changed?
            then 
                timeNow = Time.now
                self.fullChangelog = "<br>UTAS D3 QN changed from:  " + 
                "#{self.d3QN_was}" + "    to  " + "#{self.d3QN}" + 
                " on " + "#{timeNow.month} / " + 
                "#{timeNow.day} / " + "#{timeNow.year} " + "</br>" +
                "#{self.fullChangelog}"
        end
        if self.qn_changed?
            then 
                timeNow = Time.now
                self.fullChangelog = "<br>PW QN changed from:  " + 
                "#{self.qn_was}" + "    to  " + "#{self.qn}" + 
                " on " + "#{timeNow.month} / " + 
                "#{timeNow.day} / " + "#{timeNow.year} " + "</br>" +
                "#{self.fullChangelog}"
        end
        if self.status_changed?
            then 
                timeNow = Time.now
                self.fullChangelog = "<br>Status changed from:  " + 
                "#{self.status_was}" + "    to  " + "#{self.status}" + 
                " on " + "#{timeNow.month} / " + 
                "#{timeNow.day} / " + "#{timeNow.year} " + "</br>" +
                "#{self.fullChangelog}"
        end
        if self.owner_changed?
            then 
                timeNow = Time.now
                self.fullChangelog = "<br>Owner changed from:  " + 
                "#{self.owner_was}" + "    to  " + "#{self.owner}" + 
                " on " + "#{timeNow.month} / " + 
                "#{timeNow.day} / " + "#{timeNow.year} " + "</br>" +
                "#{self.fullChangelog}"
        end
        if self.product_changed?
            then 
                timeNow = Time.now
                self.fullChangelog = "<br>Product changed from:  " + 
                "#{self.product_was}" + "    to  " + "#{self.product}" + 
                " on " + "#{timeNow.month} / " + 
                "#{timeNow.day} / " + "#{timeNow.year} " + "</br>" +
                "#{self.fullChangelog}"
        end
        if self.program_changed?
            then 
                timeNow = Time.now
                self.fullChangelog = "<br>Program changed from:  " + 
                "#{self.program_was}" + "    to  " + "#{self.program}" + 
                " on " + "#{timeNow.month} / " + 
                "#{timeNow.day} / " + "#{timeNow.year} " + "</br>" +
                "#{self.fullChangelog}"
        end
        if self.removalLocation_changed?
            then 
                timeNow = Time.now
                self.fullChangelog = "<br>Removal location changed from:  " + 
                "#{self.removalLocation_was}" + "    to  " + "#{self.removalLocation}" + 
                " on " + "#{timeNow.month} / " + 
                "#{timeNow.day} / " + "#{timeNow.year} " + "</br>" +
                "#{self.fullChangelog}"
        end
        if self.removalDate_changed?
            then 
                timeNow = Time.now
                self.fullChangelog = "<br>Removal date changed from:  " + 
                "#{self.removalDate_was}" + "    to  " + "#{self.removalDate}" + 
                " on " + "#{timeNow.month} / " + 
                "#{timeNow.day} / " + "#{timeNow.year} " + "</br>" +
                "#{self.fullChangelog}"
        end
        if self.serialNum_changed?
            then 
                timeNow = Time.now
                self.fullChangelog = "<br>Serial number changed from:  " + 
                "#{self.serialNum_was}" + "    to  " + "#{self.serialNum}" + 
                " on " + "#{timeNow.month} / " + 
                "#{timeNow.day} / " + "#{timeNow.year} " + "</br>" +
                "#{self.fullChangelog}"
        end
    end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :set_record, only: [:show, :edit, :update, :destroy]

  # GET /records
  # GET /records.json
  def index
    @records = Record.all
    @records = @records.order(:product, :removalDate)

    convert_to_excel_option
  end
  
  # Resolved records kept around for future analysis/charts/etc
  def resolved
    @records = Record.where(resolved: true)
    @records = @records.order(:product, :removalDate)
    
    convert_to_excel_option
  end

  # Active refers to records that still need to be tracked
  def active
    @records = Record.where(resolved: false)
    @records = @records.order(:product, :removalDate)
    
    convert_to_excel_option
  end
  
  # Supports combined searches, excel export will export only the records in the current view (params persist)
  def search
    @records = Record.all.order(:product, :removalDate)
    if params.has_key? :record
      then @records = Record.matchesSearch(params[:record][:snQuery], 
                                           params[:record][:productQuery], 
                                           params[:record][:supplierQuery],
                                           params[:record][:statusQuery]).order(:product, :removalDate)
    end
    
    convert_to_excel_option
  end
  
  # GET /records/1
  # GET /records/1.json
  def show
  end

  # GET /records/new
  def new
    @record = Record.new
    @partNums = (Product.all.collect { |p| p.prodNum}).uniq.sort
    @partSuppliers = (Product.all.collect { |p| p.prodSupplier}).uniq.sort
    @partOwners = (Product.all.collect { |p| p.prodUTASowners}).uniq.sort
  end
  
  def narrow_choices
    @partNums = Product.numAssociatedWithPart(params[:product_choice]).collect{|p| p.prodNum}.uniq.sort
    @partSuppliers = Product.numAssociatedWithPart(params[:product_choice]).collect{|p| p.prodNum}.uniq.sort
    @partOwners = Product.numAssociatedWithPart(params[:product_choice]).collect{|p| p.prodNum}.uniq.sort
  end
  
  # GET /records/1/edit
  def edit
    @partNums = (Product.all.collect { |p| p.prodNum}).uniq.sort
    @partSuppliers = (Product.all.collect { |p| p.prodSupplier}).uniq.sort
    @partOwners = (Product.all.collect { |p| p.prodUTASowners}).uniq.sort
  end

  # POST /records
  # POST /records.json
  def create
    @record = Record.new(record_params)

    respond_to do |format|
      if @record.save
        format.html { redirect_to @record, notice: 'Return information was successfully created.' }
        format.json { render :show, status: :created, location: @record }
      else
        format.html { render :new }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /records/1
  # PATCH/PUT /records/1.json
  def update
    respond_to do |format|
      if @record.update(record_params)
        format.html { redirect_to @record, notice: 'Return information was successfully updated.' }
        format.json { render :show, status: :ok, location: @record }
      else
        format.html { render :edit }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /records/1
  # DELETE /records/1.json
  # FIXME : Disallow permanent deletions (maybe)
  def destroy
    @record.destroy
    respond_to do |format|
      format.html { redirect_to records_url, notice: 'Record was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_record
      @record = Record.find(params[:id])
    end
    
    def convert_to_excel_option
      respond_to do |format|
        format.html 
        # FIXME : C'mon Jacob, you can do better
        format.csv { render text: @records.to_csv( @records ) }
        format.xlsx do
          send_excel
        end
      end
    end
    
    # This converts the current set of records, @records, to an xlsx format, and sends it to the stream
    def send_excel
      p = Axlsx::Package.new
        wb = p.workbook
        wb.add_worksheet(name: "Records") do |sheet|
          sheet.add_row ["Serial Number", "Removal Date", "Removal Location", 
          "Program", "Product", "Part Number", "Supplier", "Owner", "Status", 
          "PW QN", "UTAS D3 QN", "UTAS V2 QN", "PW PO", "UTAS PO", 
          "Action Required", "Removal Reason", "Comments", "Resolved?"]
          @records.each do |record|
            sheet.add_row [record.serialNum, record.removalDate, 
              record.removalLocation, record.program, record.product, 
              record.partNum, record.supplier, record.owner, record.status, 
              record.qn, record.d3QN, record.v2QN, record.pwPO, record.utasPO, 
              record.actionRequiredBy, record.removalReason, record.comments, 
              record.resolved]
          end
        end
      
      # FIXME : Make filename change based on the view
      send_data p.to_stream.read, type: "application/xlsx", filename: "Returns_excel_export.xlsx"
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def record_params
      params.require(:record).permit(:serialNum, :product, :partNum, 
      :removalDate, :owner, :status, :location, :resolveBy, :removalReason, 
      :comments, :supplier, :utasPO, :pwPO, :qn, :resolved, :removalLocation,
      :program, :d3QN, :v2QN, :actionRequiredBy)
    end
end

app/helpers/records_helper.rb
module RecordsHelper
  def Record::matchesSearch(snIn = "", productIn = "", supplierIn = "", statusIn = "", records = Record.all)
    if !snIn.empty?
      then records = records.serialNum(snIn)
    end
    if !productIn.empty?
      then records = records.product(productIn)
    end
    if !supplierIn.empty?
      then records = records.supplier(supplierIn)
    end
    if !statusIn.empty?
      then records = records.status(statusIn)
    end
    
    return records
  end
end

app/views/records/_changelog.html.erb
<div>
  All previous changes (organized most to least recent): 
</div>
<div>
  <%= simple_format(record.fullChangelog) %>
</div>

app/views/records/_form.html.erb
<script src="records.js.coffe"></script>

<%= form_for(@record) do |f| %>
  <% if @record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@record.errors.count, "error") %> prohibited this record from being saved:</h2>

      <ul>
      <% @record.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <table class="boo">
    <tr>
      <th class="field">
      <%= f.label :serialNum, "Serial Number" %>
      </th>
      <th class="field">
      <%= f.label :removalDate, "Removal Date" %>
      </th>
      <th class="field">
      <%= f.label :removalLocation, "Removal Location" %>
      </th>
      <th class="field">
      <%= f.label :program, "Program" %>
      </th>
    </tr>
    <tr>
      <td class="field">
        <%= f.text_field :serialNum %>
      </td>
      <td class="field">
        <%= f.date_select :removalDate %>
      </td>
      <td class="field">
        <%= f.text_field :removalLocation %>
      </td>
      <td class="field">
        <%= f.text_field :program %>
      </td>
    </tr>
  </table>
  
  <table class="boo">
    <tr>
      <th class="field">
      <%= f.label :product %>
      </th>
      <th class="field">
      <%= f.label :partNum, "Part Number" %>
      </th>
      <th class="field">
      <%= f.label :supplier %>
      </th>
      <th class="field">
      <%= f.label :owner %>
      </th>
      <th class="field">
      <%= f.label :status %>
      </th>
    </tr>
    <tr>
      <td class="field">
        <%= select("record", "product", (Product.all.collect { |p| p.prodName}).uniq.sort, 
                   {include_blank: true}, { class: 'part_name_select' }) %>
      </td>
      <td class="field">
        <%= select("record", "partNum", @partNums, 
                   {include_blank: true}, { class: 'part_num_select' }) %>
      </td>
      <td class="field">
        <%= select("record", "supplier", @partSuppliers, 
                   {include_blank: true}, { class: 'part_supplier_select' }) %>
      </td>
      <td class="field">
        <%= select("record", "owner", @partOwners, 
                   {include_blank: true}, { class: 'part_owner_select' }) %>
      </td>
      <td class="field">
        <%= select("record", "status", Record::STATUSES, {include_blank: true}) %>
      </td>
    </tr>
  </table>
  
  <div id="prodPathForm">
   <%= link_to("Don't see a product or associated part number here? View, edit, 
                and add to the list of parts the database tracks", products_path) %>
  </div>

  <table class="boo">
    <tr>
      <th class="field">
      <%= f.label :qn, "PW QN" %>
      </th>
      <th class="field">
      <%= f.label :d3QN, "UTAS D3 QN" %>
      </th>
      <th class="field">
      <%= f.label :v2QN, "UTAS V2 QN" %>
      </th>
      <th class="field">
      <%= f.label :pwPO, "PW PO" %>
      </th>
      <th class="field">
      <%= f.label :utasPO, "UTAS PO" %>
      </th>
    </tr>
    <tr>
      <td class="field">
        <%= f.text_field :qn %>
      </td>
      <td class="field">
        <%= f.text_field :d3QN %>
      </td>
      <td class="field">
        <%= f.text_field :v2QN %>
      </td>
      <td class="field">
        <%= f.text_field :pwPO %>
      </td>
      <td class="field">
        <%= f.text_field :utasPO %>
      </td>
    </tr>
  </table>
  
  <table class="boo">
    <tr>
      <th class="field">
      <%= f.label :actionRequiredBy, "Action Required" %>
      </th>
    </tr>
    <tr>
      <td class="field">
        <%= f.text_area :actionRequiredBy, class: "actionReq" %>
      </td>
    </tr>
  </table>
  
  <table class="boo">
    <tr>
      <th class="field">
      <%= f.label :removalReason, "Removal Reason" %>
      </th>
      <th class="field">
      <%= f.label :comments %>
      </th>
    </tr>
    <tr>
      <td class="field">
        <%= f.text_area :removalReason %>
      </td>
      <td class="field">
        <%= f.text_area :comments %>
      </td>
    </tr>
  </table>
  
  <table class="boo">
    <tr>
      <th class="field">
        <%= f.label :resolved %>
        <%= f.check_box :resolved %>
      </th>
      <th class="actions">
        <%= f.submit %>
      </th>
    </tr>
  </table>
<% end %>

app/views/records/_table.html.erb
<table class="display">


  <tbody>
    
    <tr>
      <th></th>
      <th>Serial Number</th>
      <th>Product</th>
      <th>Part Number</th>
      <th>PW QN</th>
      <th>Removal Date</th>
      <th>Supplier</th>
      <th>Status</th>
    </tr>
    
    <% @records.each do |record| %>
      <tr>
        <td><%= link_to 'Show', record %></td>
        <td><%= link_to record.serialNum, edit_record_path(record) %></td>
        <td><%= record.product %></td>
        <td><%= record.partNum %></td>
        <td><%= record.qn %></td>
        <td><%= record.removalDate %></td>
        <td><%= record.supplier %></td>
        <td><%= record.status %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/records/_xlsx_download_footer.html.erb
<p>
  Download:
  <%= link_to "CSV", url_for(request.parameters.merge({:format => "csv"})) %> | 
  <%= link_to "Excel", url_for(request.parameters.merge({:format => "xlsx"})) %>
</p>

app/views/records/active.html.erb
<p id="notice"><%= notice %></p>

<h1>Active Returns</h1>

<%= render 'table' %>

<br>

<%= render 'xlsx_download_footer' %>

app/views/records/edit.html.erb
<h1>Editing Record</h1>

<%= render 'form' %>

<%= link_to 'Show', @record %> |
<%= link_to 'Back', records_path %>

<%= render partial: "changelog", locals: {record: @record} %>

app/views/records/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Records</h1>

<%= render 'table' %>

<br>

<%= render partial: 'xlsx_download_footer'  %>

app/views/records/narrow_choices.js.erb
$('.part_num_select').empty();
<% @partNums.each do |partNum| %>
  $('.part_num_select').append($('<option value="<%= partNum %>"><%= partNum %></option>'));
<% end %>

$('.part_supplier_select').empty();
<% @partSuppliers.each do |partSupplier| %>
  $('.part_supplier_select').append($('<option value="<%= partSupplier %>"><%= partSupplier %></option>'));
<% end %>

$('.part_owner_select').empty()
<% @partOwners.each do |partOwner| %>
  $('.part_owner_select').append($('<option <%= partOwner %></option>'));
<% end %>

app/views/records/new.html.erb
<h1>New Record</h1>

<%= render 'form' %>

<%= link_to 'Back', records_path %>

app/views/records/resolved.html.erb
<p id="notice"><%= notice %></p>

<h1>Resolved Returns</h1>

<%= render 'table' %>

<br>

<%= render 'xlsx_download_footer' %>

app/views/records/search.html.erb
<%= form_for(:record, method: "get") do |f| %>

<table class="boo">
  <thead>
    <tr>
      <th> <%= f.label(:snQuery, "Serial Number:") %></th>
      <th> <%= f.label(:productQuery, "Product:") %></th>
      <th> <%= f.label(:supplierQuery, "Supplier:") %></th>
      <th> <%= f.label(:statusQuery, "Status:") %> </th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td> <%= f.text_field(:snQuery) %> </td>
      <td> <%= select("record", :productQuery, (Product.all.collect{|r| r.prodName}).uniq.sort, { include_blank: true }) %> </td>
      <td> <%= select("record", :supplierQuery, (Product.all.collect{|r| r.prodSupplier}).uniq.sort, { include_blank: true }) %> </td>
      <td> <%= select("record", :statusQuery, Record::STATUSES, { include_blank: true }) %> </td>
    </tr>
  </tbody>
</table>
<div class="foo">
  <%= f.submit("Search", :name => nil) %>
</div>
<%= render 'table' %>
<% end %>

<%= render 'xlsx_download_footer' %>

app/views/records/show.html.erb
<p id="notice"><%= notice %></p>

<table class="due">
  <tr>
    <th>Serial Number</th>
    <th>Removal Date</th>
    <th>Removal Location</th>
    <th>Program</th>
  </tr>
  <tr>
    <td> <%= @record.serialNum %> </td>
    <td> <%= @record.removalDate %> </td>
    <td> <%= @record.removalLocation %> </td>
    <td> <%= @record.program %> </td>
  </tr>
</table>

<table class="due">
  <tr>
    <th>Product</th>
    <th>Part Number</th>
    <th>Supplier</th>
    <th>Owner</th>
    <th>Status</th>
  </tr>
  <tr>
    <td> <%= @record.product %> </td>
    <td> <%= @record.partNum %> </td>
    <td> <%= @record.supplier %> </td>
    <td> <%= @record.owner %> </td>
    <td> <%= @record.status %> </td>
  </tr>
</table>

<table class="due">
  <tr>
    <th>PW QN</th>
    <th>UTAS D3 QN</th>
    <th>UTAS V2 QN</th>
    <th>pwPO</th>
    <th>utasPO</th>
  </tr>
  <tr>
    <td> <%= @record.qn %> </td>
    <td> <%= @record.d3QN %> </td>
    <td> <%= @record.v2QN %> </td>
    <td> <%= @record.pwPO %> </td>
    <td> <%= @record.utasPO %> </td>
  </tr>
</table>

<table class="boo">
    <tr>
      <th>Action Required</th>
    </tr>
    <tr>
      <td> <%= @record.actionRequiredBy %> </td>
    </tr>
</table>

<table class="due">
  <tr>
    <th>Removal Reason</th>
    <th>Comments</th>
  </tr>
  <tr>
    <td> <%= @record.removalReason %> </td>
    <td> <%= @record.comments %> </td>
  </tr>
</table>


<%= link_to 'Edit', edit_record_path(@record) %> | 
<%= link_to 'Destroy', @record, method: :delete, data: { confirm: 'THIS ACTION CANNOT BE UNDONE. PLEASE CONFIRM TO CONTINUE' } %> |
<%= link_to 'Back', records_path %>